apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ClusterIP
  selector:
    componente: db
  ports:
  # the port that this service should serve on
  - port: 6379 # Puerto desde el que se van a redirigir las conexiones desde otros contenedores
    targetPort: 6379 # Puerto de la de DB de redis