name: Labo Workflow
# Cuando suceda qué lanazar el workflow
on:
  push:
    branches:
      - main

# Lo que queremos que suceda
jobs:
  tareas:
    runs-on: ubuntu-latest

    permissions:
      security-events: write
    
    steps:
     - name: Bajar código 
       uses: actions/checkout@v4

     - name: Autenticarse en DockerHub
       run: docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}

     - name: Construir la imagen con la última verisón
       run: docker build -t aingerubeor/as-laboratorio-8-web ./app

     - name: Subir la imagen al respositorio de DockerHub
       run: docker push aingerubeor/as-laboratorio-8-web

     - name: Autenticarse en Google Cloud
       uses: google-github-actions/auth@v1
       with:
         project_id: ${{ secrets.GCP_PROJECT_ID }}
         credentials_json: ${{ secrets.GCP_ACCESS_TOKEN }}

     - name: Autenticarse en GKE
       uses: simenandre/setup-gke-gcloud-auth-plugin@v1

     - name: Configurar kubectl
       uses: google-github-actions/get-gke-credentials@v1
       with:
         cluster_name: autopilot-cluster-1
         location: europe-west4
